In [125]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy.stats import chi2_contingency

In [126]:
df = pd.read_csv('/media/prince/5A4E832F4E83034D/Fraud-Detector-ML/Data/Fraud_Data.csv')
for i in df.columns:
    print(i)

transaction_id
is_fraud
transaction_time
transaction_amount
card_network
card_type
purchaser_email_domain
device_type
is_identity_seen_before
user_os
user_browser
environment
environment_freq
environment_risk
time_hour
time_day
time_diff
time_diff_min
amt_log
amt_bins
new_day
day_id
day_of_week
time_diff_log

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           590540 non-null  int64
 1   is_fraud                 590540 non-null  int64
 2   transaction_time         590540 non-null  int64
 3   transaction_amount       590540 non-null  float64
 4   card_network             588963 non-null  object
 5   card_type                588969 non-null  object
 6   purchaser_email_domain   496084 non-null  object
 7   device_type              140810 non-null  object
 8   is_identity_seen_before  129340 non-null  object
 9   user_os                  144233 non-null  object
 10  user_browser             144233 non-null  object
 11  environment              144233 non-null  object
 12  environment_freq         144233 non-null  float64
 13  environment_risk         144233 non-null  float64
 14  time_hour                590540 non-null  int64
 15  time_day                 590540 non-null  float64
 16  time_diff                590539 non-null  float64
 17  time_diff_min            590539 non-null  float64
 18  amt_log                  590540 non-null  float64
 19  amt_bins                 590540 non-null  int64
 20  new_day                  590540 non-null  bool
 21  day_id                   590540 non-null  int64
 22  day_of_week              590540 non-null  int64
 23  time_diff_log            590539 non-null  float64
dtypes: bool(1), float64(8), int64(7), object(8)
memory usage: 104.2+ MB

In [128]:
df['environment_risk'] = df['environment_risk'].astype(object)

num_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(exclude='number').columns.tolist()

df[num_cols] = df[num_cols].astype(float)
df[num_cols] = df[num_cols].fillna(0)

bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(object)

df[cat_cols] = df[cat_cols].fillna('missing')

In [129]:
df['is_fraud'] = df['is_fraud'].astype(object)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           590540 non-null  float64
 1   is_fraud                 590540 non-null  object
 2   transaction_time         590540 non-null  float64
 3   transaction_amount       590540 non-null  float64
 4   card_network             590540 non-null  object
 5   card_type                590540 non-null  object
 6   purchaser_email_domain   590540 non-null  object
 7   device_type              590540 non-null  object
 8   is_identity_seen_before  590540 non-null  object
 9   user_os                  590540 non-null  object
 10  user_browser             590540 non-null  object
 11  environment              590540 non-null  object
 12  environment_freq         590540 non-null  float64
 13  environment_risk         590540 non-null  object
 14  time_hour                590540 non-null  float64
 15  time_day                 590540 non-null  float64
 16  time_diff                590540 non-null  float64
 17  time_diff_min            590540 non-null  float64
 18  amt_log                  590540 non-null  float64
 19  amt_bins                 590540 non-null  float64
 20  new_day                  590540 non-null  bool
 21  day_id                   590540 non-null  float64
 22  day_of_week              590540 non-null  float64
 23  time_diff_log            590540 non-null  float64
dtypes: bool(1), float64(13), object(10)
memory usage: 104.2+ MB

In [130]:
df['device_type'].unique()

array(['missing', 'mobile', 'desktop'], dtype=object)

In [131]:
df['user_os'].unique()

array(['missing', 'Android', 'iOS', 'Other', 'macOS', 'Windows', 'Linux'],
      dtype=object)

In [132]:
df['device_typ_os'] = df['device_type'] + '_' + df['user_os']

In [133]:
df['device_typ_os'].unique()

array(['missing_missing', 'mobile_Android', 'mobile_iOS', 'desktop_Other',
       'desktop_macOS', 'desktop_Windows', 'missing_Other',
       'desktop_Linux', 'mobile_Other', 'mobile_macOS', 'desktop_Android',
       'mobile_Linux', 'mobile_Windows', 'desktop_iOS'], dtype=object)

In [134]:
ct = pd.crosstab(df['device_typ_os'], df['is_fraud'])
(pd.crosstab(df['device_typ_os'], df['is_fraud'], normalize='index')) * 100

is_fraud                0.0        1.0
device_typ_os
desktop_Android  100.000000   0.000000
desktop_Linux     92.741935   7.258065
desktop_Other     88.424733  11.575267
desktop_Windows   96.547029   3.452971
desktop_iOS      100.000000   0.000000
desktop_macOS     97.804303   2.195697
missing_Other     96.874087   3.125913
missing_missing   97.906150   2.093850
mobile_Android    91.399556   8.600444
mobile_Linux      80.000000  20.000000
mobile_Other      86.885524  13.114476
mobile_Windows   100.000000   0.000000
mobile_iOS        93.731358   6.268642
mobile_macOS     100.000000   0.000000

In [135]:
chi2, p, dof, exp = chi2_contingency(ct)
print(p)
n = ct.values.sum()
cramers_v = np.sqrt(chi2 / (n * (min(ct.shape) - 1)))
print(cramers_v)

0.0
0.17594492676742396

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           590540 non-null  float64
 1   is_fraud                 590540 non-null  object
 2   transaction_time         590540 non-null  float64
 3   transaction_amount       590540 non-null  float64
 4   card_network             590540 non-null  object
 5   card_type                590540 non-null  object
 6   purchaser_email_domain   590540 non-null  object
 7   device_type              590540 non-null  object
 8   is_identity_seen_before  590540 non-null  object
 9   user_os                  590540 non-null  object
 10  user_browser             590540 non-null  object
 11  environment              590540 non-null  object
 12  environment_freq         590540 non-null  float64
 13  environment_risk         590540 non-null  object
 14  time_hour                590540 non-null  float64
 15  time_day                 590540 non-null  float64
 16  time_diff                590540 non-null  float64
 17  time_diff_min            590540 non-null  float64
 18  amt_log                  590540 non-null  float64
 19  amt_bins                 590540 non-null  float64
 20  new_day                  590540 non-null  bool
 21  day_id                   590540 non-null  float64
 22  day_of_week              590540 non-null  float64
 23  time_diff_log            590540 non-null  float64
 24  device_typ_os            590540 non-null  object
dtypes: bool(1), float64(13), object(11)
memory usage: 108.7+ MB

In [137]:
df['known_env_risk'] = df['environment_risk'].astype(str) + '_' + df['is_identity_seen_before'].astype(str)

In [138]:
ct = pd.crosstab(df['known_env_risk'], df['is_fraud'])
((pd.crosstab(df['known_env_risk'], df['is_fraud'], normalize='index')) * 100).round(3)

is_fraud            0.0     1.0
known_env_risk
0.0_Found        87.301  12.699
0.0_New          94.594   5.406
0.0_missing      90.330   9.670
1.0_Found        94.491   5.509
1.0_New          96.933   3.067
1.0_missing      96.570   3.430
2.0_Found        80.628  19.372
2.0_New          90.664   9.336
2.0_missing      69.259  30.741
missing_missing  97.906   2.094

In [139]:
chi2, p, dof, exp = chi2_contingency(ct)
print(p)
n = ct.values.sum()
cramers_v = np.sqrt(chi2 / (n * (min(ct.shape) - 1)))
print(cramers_v)

0.0
0.17123194300282718

In [140]:
df['time_diff_log'].describe()

count    590540.000000
mean          2.610262
std           1.160858
min           0.000000
25%           1.791759
50%           2.639057
75%           3.401197
max           8.328209
Name: time_diff_log, dtype: float64

In [141]:
df['time_diff_bins'] = pd.qcut(df['time_diff_log'], q = 10 , labels=False)

In [142]:
# import warnings
# warnings.filterwarnings('ignore')

# # ---------- 1. Define your categorical columns (all treated as categorical) ----------
# # Use your final DataFrame after preprocessing (no missing values, consistent types)
# # The columns you provided, with types adjusted:
# categorical_cols = [
#     'is_fraud',               # target
#     'card_network',
#     'card_type',
#     'purchaser_email_domain',
#     'device_type',
#     'is_identity_seen_before',
#     'user_os',
#     'user_browser',
#     'environment_risk',       # already object (categorical)
#     'time_hour',              # you want to treat as categorical
#     'amt_bins',               # binned amount
#     'day_of_week',            # already numeric but few categories
#     'device_typ_os',          # engineered feature
#     'known_env_risk',
#     'time_diff_bins'          # engineered feature
# ]

# # Ensure all are of type 'object' or 'category' for consistent handling
# df[categorical_cols] = df[categorical_cols].astype('object')

# # ---------- 2. Fill any remaining missing values with 'missing' (though you said none) ----------
# df_filled = df[categorical_cols].fillna('missing')

# # ---------- 3. Function to compute Cramér's V ----------
# def cramers_v(confusion_matrix):
#     """Calculate Cramér's V from a contingency table."""
#     chi2 = chi2_contingency(confusion_matrix)[0]
#     n = confusion_matrix.sum().sum()
#     phi2 = chi2 / n
#     r, k = confusion_matrix.shape
#     phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
#     rcorr = r - ((r-1)**2)/(n-1)
#     kcorr = k - ((k-1)**2)/(n-1)
#     return np.sqrt(phi2corr / min((kcorr-1), (rcorr-1)))

# # ---------- 4. Compute all pairwise associations ----------
# # We'll store results in a dictionary of dataframes, one per feature
# results_per_feature = {}

# for i, feat1 in enumerate(categorical_cols):
#     records = []
#     for j, feat2 in enumerate(categorical_cols):
#         if i == j:
#             continue  # skip self
#         # Create contingency table
#         crosstab = pd.crosstab(df_filled[feat1], df_filled[feat2])
#         try:
#             chi2, p, dof, expected = chi2_contingency(crosstab)
#             v = cramers_v(crosstab)
#         except:
#             chi2, p, v = np.nan, np.nan, np.nan
        
#         records.append({
#             'feature_2': feat2,
#             'cramers_v': v,
#             'p_value': p,
#             'chi2': chi2
#         })
    
#     # Convert to DataFrame and sort by Cramér's V descending
#     df_pair = pd.DataFrame(records)
#     df_pair = df_pair.sort_values('cramers_v', ascending=False).reset_index(drop=True)
#     results_per_feature[feat1] = df_pair

# # ---------- 5. Display results per feature ----------
# for feat, df_res in results_per_feature.items():
#     print(f"\n{'='*80}")
#     print(f" Associations for feature: {feat}")
#     print('='*80)
#     print(df_res.to_string(index=False))
#     print()  # blank line for readability

In [152]:
df2 = df.drop(columns=['is_fraud', 'transaction_id', 'transaction_time', 
                       'time_day', 'time_diff', 'time_diff_min', 
                       'amt_log', 'new_day', 'day_id', 'day_of_week', 'transaction_amount', 'environment', 'environment_freq', 'time_diff_log'])
for i in df2.columns:
    '___________*************************_________'
    print(i)
    print(df[i].unique())

    '___________***************_________'

card_network
['discover' 'mastercard' 'visa' 'american express' 'missing']
card_type
['credit' 'debit' 'missing' 'debit or credit' 'charge card']
purchaser_email_domain
['missing' 'gmail.com' 'outlook.com' 'yahoo.com' 'mail.com'
 'anonymous.com' 'hotmail.com' 'verizon.net' 'aol.com' 'me.com'
 'comcast.net' 'optonline.net' 'cox.net' 'charter.net' 'rocketmail.com'
 'prodigy.net.mx' 'embarqmail.com' 'icloud.com' 'live.com.mx' 'gmail'
 'live.com' 'att.net' 'juno.com' 'ymail.com' 'sbcglobal.net'
 'bellsouth.net' 'msn.com' 'q.com' 'yahoo.com.mx' 'centurylink.net'
 'servicios-ta.com' 'earthlink.net' 'hotmail.es' 'cfl.rr.com'
 'roadrunner.com' 'netzero.net' 'gmx.de' 'suddenlink.net'
 'frontiernet.net' 'windstream.net' 'frontier.com' 'outlook.es' 'mac.com'
 'netzero.com' 'aim.com' 'web.de' 'twc.com' 'cableone.net' 'yahoo.fr'
 'yahoo.de' 'yahoo.es' 'sc.rr.com' 'ptd.net' 'live.fr' 'yahoo.co.uk'
 'hotmail.fr' 'hotmail.de' 'hotmail.co.uk' 'protonmail.com' 'yahoo.co.jp']
device_type
['missing' 'mobile' 'desktop']
is_identity_seen_before
['missing' 'New' 'Found']
user_os
['missing' 'Android' 'iOS' 'Other' 'macOS' 'Windows' 'Linux']
user_browser
['missing' 'Samsung' 'Safari' 'Chrome' 'Other' 'Edge' 'Firefox' 'IE'
 'Opera' 'Android WebView']
environment_risk
['missing' 1.0 0.0 2.0]
time_hour
['0.0' '1.0' '2.0' '3.0' '4.0' '5.0' '6.0' '7.0' '8.0' '9.0' '10.0' '11.0'
 '12.0' '13.0' '14.0' '15.0' '16.0' '17.0' '18.0' '19.0' '20.0' '21.0'
 '22.0' '23.0']
amt_bins
['4.0' '1.0' '3.0' '2.0' '7.0' '9.0' '0.0' '6.0' '5.0' '8.0']
device_typ_os
['missing_missing' 'mobile_Android' 'mobile_iOS' 'desktop_Other'
 'desktop_macOS' 'desktop_Windows' 'missing_Other' 'desktop_Linux'
 'mobile_Other' 'mobile_macOS' 'desktop_Android' 'mobile_Linux'
 'mobile_Windows' 'desktop_iOS']
known_env_risk
['missing_missing' '1.0_New' '0.0_New' '0.0_Found' '1.0_Found'
 '1.0_missing' '0.0_missing' '2.0_New' '2.0_Found' '2.0_missing']
time_diff_bins
['0' '9' '7' '2' '1' '4' '3' '6' '8' '5']
card_net_user_os
['discover_missing' 'mastercard_missing' 'visa_missing'
 'mastercard_Android' 'visa_iOS' 'mastercard_Other' 'visa_macOS'
 'mastercard_Windows' 'visa_Other' 'american express_Android'
 'visa_Android' 'visa_Windows' 'visa_Linux' 'american express_macOS'
 'mastercard_macOS' 'american express_iOS' 'mastercard_iOS'
 'american express_Windows' 'discover_Windows' 'discover_iOS'
 'discover_Other' 'discover_Android' 'discover_macOS'
 'american express_Other' 'mastercard_Linux' 'missing_Android'
 'american express_missing' 'discover_Linux' 'american express_Linux'
 'missing_missing' 'missing_Windows' 'missing_macOS' 'missing_iOS'
 'missing_Other']
card_net_id_seen
['discover_missing' 'mastercard_missing' 'visa_missing' 'mastercard_New'
 'visa_New' 'mastercard_Found' 'visa_Found' 'american express_Found'
 'american express_New' 'discover_New' 'discover_Found'
 'american express_missing' 'missing_New' 'missing_Found'
 'missing_missing']
card_type_user_os
['credit_missing' 'debit_missing' 'credit_Android' 'debit_iOS'
 'credit_Other' 'debit_Other' 'debit_macOS' 'credit_Windows'
 'debit_Android' 'debit_Linux' 'credit_iOS' 'credit_macOS' 'debit_Windows'
 'credit_Linux' 'missing_Android' 'debit or credit_missing'
 'charge card_Other' 'missing_missing' 'missing_macOS' 'missing_iOS'
 'missing_Windows' 'missing_Other' 'charge card_Windows' 'charge card_iOS']
card_type_id_seen
['credit_missing' 'debit_missing' 'credit_New' 'debit_New' 'credit_Found'
 'debit_Found' 'missing_New' 'debit or credit_missing' 'charge card_New'
 'missing_missing' 'charge card_Found' 'missing_Found'
 'charge card_missing']
pemail_dev_type
['missing_missing' 'gmail.com_missing' 'outlook.com_missing'
 'yahoo.com_missing' 'gmail.com_mobile' 'mail.com_missing'
 'anonymous.com_mobile' 'gmail.com_desktop' 'hotmail.com_desktop'
 'verizon.net_missing' 'aol.com_missing' 'aol.com_desktop'
 'yahoo.com_desktop' 'me.com_missing' 'missing_mobile'
 'anonymous.com_missing' 'outlook.com_desktop' 'anonymous.com_desktop'
 'hotmail.com_missing' 'missing_desktop' 'outlook.com_mobile'
 'comcast.net_missing' 'optonline.net_missing' 'cox.net_missing'
 'charter.net_desktop' 'comcast.net_mobile' 'rocketmail.com_missing'
 'prodigy.net.mx_missing' 'yahoo.com_mobile' 'comcast.net_desktop'
 'optonline.net_desktop' 'embarqmail.com_mobile' 'hotmail.com_mobile'
 'icloud.com_missing' 'aol.com_mobile' 'live.com.mx_mobile'
 'gmail_missing' 'live.com_missing' 'icloud.com_mobile'
 'live.com.mx_desktop' 'att.net_missing' 'juno.com_desktop'
 'ymail.com_missing' 'sbcglobal.net_missing' 'juno.com_missing'
 'charter.net_missing' 'bellsouth.net_missing' 'att.net_desktop'
 'msn.com_desktop' 'q.com_missing' 'yahoo.com.mx_desktop'
 'msn.com_missing' 'centurylink.net_missing' 'cox.net_mobile'
 'servicios-ta.com_mobile' 'me.com_desktop' 'earthlink.net_missing'
 'hotmail.es_mobile' 'hotmail.es_desktop' 'cfl.rr.com_missing'
 'roadrunner.com_missing' 'msn.com_mobile' 'live.com_mobile'
 'live.com_desktop' 'verizon.net_mobile' 'cox.net_desktop'
 'bellsouth.net_mobile' 'icloud.com_desktop' 'sbcglobal.net_desktop'
 'me.com_mobile' 'verizon.net_desktop' 'netzero.net_missing'
 'live.com.mx_missing' 'gmx.de_missing' 'suddenlink.net_missing'
 'hotmail.es_missing' 'frontiernet.net_missing' 'windstream.net_missing'
 'mail.com_desktop' 'frontier.com_desktop' 'frontiernet.net_desktop'
 'bellsouth.net_desktop' 'yahoo.com.mx_missing' 'charter.net_mobile'
 'outlook.es_desktop' 'suddenlink.net_desktop' 'roadrunner.com_mobile'
 'mac.com_desktop' 'netzero.com_missing' 'frontier.com_missing'
 'aim.com_missing' 'mac.com_missing' 'yahoo.com.mx_mobile'
 'att.net_mobile' 'outlook.es_mobile' 'earthlink.net_mobile'
 'web.de_desktop' 'mail.com_mobile' 'sbcglobal.net_mobile'
 'twc.com_desktop' 'ymail.com_mobile' 'embarqmail.com_missing'
 'cableone.net_missing' 'twc.com_mobile' 'web.de_mobile' 'yahoo.fr_mobile'
 'yahoo.de_desktop' 'windstream.net_desktop' 'gmail_mobile'
 'twc.com_missing' 'rocketmail.com_mobile' 'ymail.com_desktop'
 'cfl.rr.com_desktop' 'yahoo.es_desktop' 'web.de_missing' 'mac.com_mobile'
 'earthlink.net_desktop' 'frontiernet.net_mobile' 'gmail_desktop'
 'sc.rr.com_missing' 'ptd.net_missing' 'live.fr_mobile' 'q.com_desktop'
 'prodigy.net.mx_desktop' 'yahoo.co.uk_desktop' 'gmx.de_mobile'
 'yahoo.de_missing' 'embarqmail.com_desktop' 'hotmail.fr_desktop'
 'optonline.net_mobile' 'hotmail.de_desktop' 'roadrunner.com_desktop'
 'outlook.es_missing' 'hotmail.co.uk_missing' 'netzero.net_mobile'
 'cableone.net_desktop' 'aim.com_mobile' 'yahoo.co.uk_mobile'
 'yahoo.fr_desktop' 'yahoo.es_missing' 'rocketmail.com_desktop'
 'hotmail.fr_mobile' 'gmx.de_desktop' 'yahoo.co.uk_missing'
 'protonmail.com_missing' 'centurylink.net_desktop' 'hotmail.co.uk_mobile'
 'netzero.com_desktop' 'sc.rr.com_mobile' 'cfl.rr.com_mobile'
 'centurylink.net_mobile' 'ptd.net_mobile' 'windstream.net_mobile'
 'sc.rr.com_desktop' 'netzero.com_mobile' 'prodigy.net.mx_mobile'
 'q.com_mobile' 'netzero.net_desktop' 'yahoo.de_mobile'
 'yahoo.co.jp_mobile' 'suddenlink.net_mobile' 'frontier.com_mobile'
 'ptd.net_desktop' 'juno.com_mobile' 'yahoo.es_mobile'
 'protonmail.com_desktop' 'aim.com_desktop' 'yahoo.fr_missing'
 'hotmail.co.uk_desktop' 'hotmail.de_mobile' 'cableone.net_mobile'
 'protonmail.com_mobile' 'hotmail.fr_missing' 'live.fr_desktop'
 'yahoo.co.jp_desktop' 'live.fr_missing' 'hotmail.de_missing']
pemail_id_seen
['missing_missing' 'gmail.com_missing' 'outlook.com_missing'
 'yahoo.com_missing' 'gmail.com_New' 'mail.com_missing'
 'anonymous.com_New' 'gmail.com_Found' 'hotmail.com_New'
 'verizon.net_missing' 'aol.com_missing' 'aol.com_Found' 'yahoo.com_Found'
 'me.com_missing' 'missing_Found' 'anonymous.com_missing'
 'outlook.com_New' 'hotmail.com_missing' 'anonymous.com_Found'
 'comcast.net_missing' 'optonline.net_missing' 'cox.net_missing'
 'charter.net_New' 'comcast.net_New' 'rocketmail.com_missing'
 'comcast.net_Found' 'prodigy.net.mx_missing' 'yahoo.com_New'
 'optonline.net_Found' 'embarqmail.com_New' 'icloud.com_missing'
 'aol.com_New' 'live.com.mx_missing' 'hotmail.com_Found' 'gmail_missing'
 'live.com_missing' 'icloud.com_New' 'live.com.mx_Found'
 'icloud.com_Found' 'att.net_missing' 'juno.com_New' 'ymail.com_missing'
 'sbcglobal.net_missing' 'juno.com_missing' 'charter.net_missing'
 'bellsouth.net_missing' 'att.net_New' 'msn.com_Found' 'outlook.com_Found'
 'missing_New' 'msn.com_New' 'q.com_missing' 'yahoo.com.mx_New'
 'msn.com_missing' 'live.com.mx_New' 'centurylink.net_missing'
 'cox.net_New' 'yahoo.com.mx_Found' 'servicios-ta.com_Found'
 'me.com_Found' 'earthlink.net_missing' 'hotmail.es_New'
 'hotmail.es_Found' 'cfl.rr.com_missing' 'roadrunner.com_missing'
 'live.com_New' 'optonline.net_New' 'verizon.net_New' 'verizon.net_Found'
 'bellsouth.net_New' 'bellsouth.net_Found' 'sbcglobal.net_Found'
 'me.com_New' 'cox.net_Found' 'netzero.net_missing' 'gmx.de_missing'
 'suddenlink.net_missing' 'hotmail.es_missing' 'frontiernet.net_missing'
 'live.com_Found' 'windstream.net_missing' 'mail.com_Found'
 'frontier.com_Found' 'frontiernet.net_Found' 'sbcglobal.net_New'
 'yahoo.com.mx_missing' 'outlook.es_Found' 'suddenlink.net_Found'
 'att.net_Found' 'roadrunner.com_New' 'mac.com_New' 'netzero.com_missing'
 'frontier.com_missing' 'aim.com_missing' 'mac.com_missing'
 'earthlink.net_New' 'web.de_Found' 'mail.com_New' 'charter.net_Found'
 'twc.com_New' 'ymail.com_New' 'embarqmail.com_missing' 'mac.com_Found'
 'cableone.net_missing' 'web.de_missing' 'yahoo.fr_missing'
 'yahoo.de_Found' 'windstream.net_New' 'gmail_New' 'earthlink.net_Found'
 'twc.com_missing' 'rocketmail.com_New' 'ymail.com_Found'
 'cfl.rr.com_Found' 'yahoo.es_Found' 'frontiernet.net_New' 'gmail_Found'
 'sc.rr.com_missing' 'ptd.net_missing' 'live.fr_missing' 'q.com_New'
 'prodigy.net.mx_Found' 'yahoo.co.uk_Found' 'gmx.de_New'
 'yahoo.de_missing' 'windstream.net_Found' 'web.de_New'
 'embarqmail.com_Found' 'hotmail.fr_Found' 'q.com_Found'
 'hotmail.de_Found' 'frontier.com_New' 'roadrunner.com_Found'
 'cfl.rr.com_New' 'outlook.es_New' 'outlook.es_missing' 'juno.com_Found'
 'hotmail.co.uk_missing' 'netzero.net_Found' 'cableone.net_Found'
 'aim.com_Found' 'yahoo.fr_New' 'yahoo.es_missing' 'hotmail.fr_New'
 'yahoo.co.uk_missing' 'protonmail.com_missing' 'centurylink.net_Found'
 'yahoo.fr_Found' 'hotmail.co.uk_Found' 'netzero.com_Found'
 'yahoo.co.uk_New' 'sc.rr.com_New' 'centurylink.net_New'
 'prodigy.net.mx_New' 'netzero.com_New' 'netzero.net_New'
 'rocketmail.com_Found' 'ptd.net_New' 'hotmail.fr_missing'
 'yahoo.co.jp_missing' 'suddenlink.net_New' 'ptd.net_Found'
 'twc.com_Found' 'aim.com_New' 'yahoo.es_New' 'protonmail.com_Found'
 'cableone.net_New' 'hotmail.co.uk_New' 'gmx.de_Found' 'yahoo.de_New'
 'protonmail.com_New' 'hotmail.de_missing' 'sc.rr.com_Found'
 'yahoo.co.jp_New' 'yahoo.co.jp_Found' 'live.fr_New' 'live.fr_Found'
 'hotmail.de_New']
pemail_env_risk
['missing_missing' 'gmail.com_missing' 'outlook.com_missing'
 'yahoo.com_missing' 'gmail.com_1.0' 'mail.com_missing'
 'anonymous.com_0.0' 'gmail.com_0.0' 'hotmail.com_0.0'
 'verizon.net_missing' 'aol.com_missing' 'aol.com_1.0' 'yahoo.com_0.0'
 'me.com_missing' 'missing_1.0' 'anonymous.com_missing' 'outlook.com_0.0'
 'hotmail.com_missing' 'comcast.net_missing' 'optonline.net_missing'
 'cox.net_missing' 'charter.net_1.0' 'comcast.net_1.0' 'yahoo.com_1.0'
 'rocketmail.com_missing' 'anonymous.com_1.0' 'prodigy.net.mx_missing'
 'comcast.net_0.0' 'optonline.net_1.0' 'embarqmail.com_1.0'
 'icloud.com_missing' 'aol.com_0.0' 'live.com.mx_0.0' 'gmail_missing'
 'live.com_missing' 'icloud.com_0.0' 'missing_0.0' 'att.net_missing'
 'juno.com_0.0' 'ymail.com_missing' 'sbcglobal.net_missing'
 'juno.com_missing' 'charter.net_missing' 'bellsouth.net_missing'
 'att.net_1.0' 'msn.com_1.0' 'missing_2.0' 'q.com_missing'
 'yahoo.com.mx_0.0' 'msn.com_missing' 'msn.com_0.0'
 'centurylink.net_missing' 'cox.net_0.0' 'gmail.com_2.0'
 'servicios-ta.com_1.0' 'yahoo.com.mx_1.0' 'me.com_0.0'
 'earthlink.net_missing' 'hotmail.es_0.0' 'hotmail.com_2.0'
 'cfl.rr.com_missing' 'comcast.net_2.0' 'roadrunner.com_missing'
 'hotmail.com_1.0' 'live.com_0.0' 'optonline.net_0.0' 'verizon.net_1.0'
 'juno.com_1.0' 'bellsouth.net_0.0' 'icloud.com_1.0' 'sbcglobal.net_0.0'
 'charter.net_0.0' 'verizon.net_0.0' 'outlook.com_2.0'
 'netzero.net_missing' 'live.com.mx_missing' 'gmx.de_1.0'
 'sbcglobal.net_1.0' 'suddenlink.net_missing' 'hotmail.es_missing'
 'frontiernet.net_missing' 'yahoo.com_2.0' 'windstream.net_missing'
 'mail.com_0.0' 'frontier.com_0.0' 'frontiernet.net_1.0' 'me.com_1.0'
 'yahoo.com.mx_missing' 'outlook.es_0.0' 'suddenlink.net_0.0'
 'roadrunner.com_0.0' 'anonymous.com_2.0' 'mac.com_0.0'
 'netzero.com_missing' 'frontier.com_missing' 'live.com_1.0'
 'aim.com_missing' 'mac.com_missing' 'att.net_0.0' 'outlook.es_2.0'
 'earthlink.net_0.0' 'web.de_1.0' 'mail.com_2.0' 'cox.net_1.0'
 'bellsouth.net_1.0' 'hotmail.es_1.0' 'twc.com_0.0' 'ymail.com_1.0'
 'mac.com_1.0' 'embarqmail.com_missing' 'outlook.com_1.0'
 'cableone.net_missing' 'gmx.de_missing' 'web.de_0.0' 'yahoo.fr_0.0'
 'yahoo.de_0.0' 'windstream.net_0.0' 'gmail_0.0' 'msn.com_2.0'
 'earthlink.net_1.0' 'twc.com_missing' 'rocketmail.com_0.0'
 'ymail.com_0.0' 'cfl.rr.com_1.0' 'yahoo.es_0.0' 'web.de_missing'
 'frontiernet.net_0.0' 'live.com_2.0' 'gmail_1.0' 'sc.rr.com_missing'
 'ptd.net_missing' 'live.fr_0.0' 'q.com_0.0' 'prodigy.net.mx_0.0'
 'yahoo.co.uk_0.0' 'gmx.de_0.0' 'yahoo.de_missing' 'windstream.net_1.0'
 'frontier.com_1.0' 'embarqmail.com_0.0' 'live.com.mx_1.0'
 'suddenlink.net_1.0' 'hotmail.fr_1.0' 'q.com_1.0' 'hotmail.de_1.0'
 'roadrunner.com_1.0' 'cfl.rr.com_0.0' 'rocketmail.com_1.0'
 'outlook.es_missing' 'aol.com_2.0' 'hotmail.co.uk_missing'
 'netzero.net_1.0' 'cableone.net_1.0' 'icloud.com_2.0' 'aim.com_0.0'
 'yahoo.fr_1.0' 'yahoo.es_missing' 'ptd.net_1.0' 'hotmail.fr_0.0'
 'yahoo.co.uk_1.0' 'protonmail.com_missing' 'centurylink.net_1.0'
 'hotmail.co.uk_0.0' 'netzero.com_0.0' 'twc.com_1.0' 'sc.rr.com_1.0'
 'ptd.net_0.0' 'cox.net_2.0' 'sc.rr.com_0.0' 'prodigy.net.mx_1.0'
 'yahoo.co.uk_missing' 'yahoo.com.mx_2.0' 'netzero.net_0.0'
 'verizon.net_2.0' 'sbcglobal.net_2.0' 'yahoo.co.jp_0.0' 'outlook.es_1.0'
 'centurylink.net_0.0' 'yahoo.de_1.0' 'q.com_2.0' 'aim.com_1.0'
 'mail.com_1.0' 'protonmail.com_1.0' 'protonmail.com_0.0' 'gmx.de_2.0'
 'ymail.com_2.0' 'att.net_2.0' 'cableone.net_0.0' 'hotmail.es_2.0'
 'juno.com_2.0' 'yahoo.fr_missing' 'charter.net_2.0' 'web.de_2.0'
 'hotmail.co.uk_2.0' 'bellsouth.net_2.0' 'live.com.mx_2.0' 'yahoo.es_1.0'
 'hotmail.de_0.0' 'mac.com_2.0' 'earthlink.net_2.0' 'netzero.com_1.0'
 'twc.com_2.0' 'aim.com_2.0' 'yahoo.co.jp_1.0' 'hotmail.fr_2.0'
 'live.fr_missing' 'live.fr_1.0' 'yahoo.co.jp_2.0' 'hotmail.fr_missing'
 'hotmail.co.uk_1.0' 'protonmail.com_2.0' 'suddenlink.net_2.0'
 'me.com_2.0']
pemail_user_os
['missing_missing' 'gmail.com_missing' 'outlook.com_missing'
 'yahoo.com_missing' 'gmail.com_Android' 'mail.com_missing'
 'anonymous.com_iOS' 'gmail.com_Other' 'hotmail.com_Other'
 'verizon.net_missing' 'aol.com_missing' 'aol.com_macOS'
 'yahoo.com_Windows' 'me.com_missing' 'missing_Android'
 'anonymous.com_missing' 'outlook.com_Other' 'anonymous.com_Other'
 'hotmail.com_missing' 'anonymous.com_Windows' 'missing_Linux'
 'comcast.net_missing' 'optonline.net_missing' 'cox.net_missing'
 'charter.net_Windows' 'gmail.com_iOS' 'comcast.net_Android'
 'yahoo.com_macOS' 'rocketmail.com_missing' 'anonymous.com_macOS'
 'gmail.com_macOS' 'prodigy.net.mx_missing' 'yahoo.com_iOS'
 'comcast.net_Windows' 'optonline.net_Windows' 'embarqmail.com_Android'
 'icloud.com_missing' 'aol.com_iOS' 'live.com.mx_Other' 'gmail_missing'
 'live.com_missing' 'icloud.com_iOS' 'missing_Windows' 'att.net_missing'
 'juno.com_macOS' 'ymail.com_missing' 'gmail.com_Windows'
 'sbcglobal.net_missing' 'comcast.net_macOS' 'missing_iOS'
 'juno.com_missing' 'yahoo.com_Other' 'hotmail.com_macOS'
 'charter.net_missing' 'hotmail.com_iOS' 'bellsouth.net_missing'
 'att.net_Windows' 'msn.com_Windows' 'missing_macOS' 'yahoo.com_Android'
 'q.com_missing' 'yahoo.com.mx_Other' 'msn.com_missing'
 'centurylink.net_missing' 'cox.net_iOS' 'aol.com_Android'
 'icloud.com_Other' 'servicios-ta.com_Other' 'aol.com_Windows'
 'me.com_macOS' 'earthlink.net_missing' 'hotmail.es_Other'
 'cfl.rr.com_missing' 'comcast.net_iOS' 'roadrunner.com_missing'
 'msn.com_iOS' 'missing_Other' 'live.com_iOS' 'live.com_Other'
 'hotmail.com_Windows' 'verizon.net_Android' 'cox.net_Windows'
 'juno.com_Windows' 'bellsouth.net_iOS' 'icloud.com_macOS'
 'sbcglobal.net_Windows' 'me.com_iOS' 'verizon.net_Windows'
 'verizon.net_macOS' 'netzero.net_missing' 'live.com.mx_missing'
 'gmx.de_Other' 'suddenlink.net_missing' 'hotmail.es_missing'
 'me.com_Windows' 'frontiernet.net_missing' 'aol.com_Other'
 'live.com_Windows' 'windstream.net_missing' 'mail.com_Windows'
 'frontier.com_Windows' 'frontiernet.net_Windows' 'me.com_Other'
 'bellsouth.net_Windows' 'yahoo.com.mx_missing' 'charter.net_iOS'
 'outlook.es_Other' 'suddenlink.net_Windows' 'roadrunner.com_iOS'
 'msn.com_macOS' 'mac.com_macOS' 'netzero.com_missing'
 'icloud.com_Windows' 'frontier.com_missing' 'live.com_Android'
 'aim.com_missing' 'mac.com_missing' 'att.net_iOS' 'earthlink.net_iOS'
 'web.de_Other' 'mail.com_Other' 'sbcglobal.net_iOS' 'optonline.net_macOS'
 'verizon.net_iOS' 'hotmail.com_Linux' 'cox.net_macOS'
 'sbcglobal.net_macOS' 'anonymous.com_Linux' 'att.net_macOS'
 'comcast.net_Other' 'twc.com_macOS' 'ymail.com_Android' 'yahoo.com_Linux'
 'mac.com_Windows' 'anonymous.com_Android' 'embarqmail.com_missing'
 'outlook.com_Windows' 'gmail.com_Linux' 'cableone.net_missing'
 'aol.com_Linux' 'gmx.de_missing' 'twc.com_iOS' 'hotmail.com_Android'
 'yahoo.fr_Other' 'yahoo.de_Other' 'windstream.net_macOS' 'gmail_iOS'
 'charter.net_macOS' 'earthlink.net_Android' 'msn.com_Other'
 'twc.com_missing' 'earthlink.net_Other' 'rocketmail.com_iOS'
 'ymail.com_Windows' 'sbcglobal.net_Android' 'ymail.com_iOS'
 'cfl.rr.com_macOS' 'bellsouth.net_Android' 'yahoo.es_Other'
 'web.de_missing' 'msn.com_Android' 'mac.com_iOS' 'earthlink.net_macOS'
 'frontiernet.net_iOS' 'gmail_Other' 'outlook.com_iOS'
 'bellsouth.net_Other' 'gmail_macOS' 'ymail.com_Other' 'sc.rr.com_missing'
 'ptd.net_missing' 'live.fr_Other' 'q.com_Windows' 'prodigy.net.mx_Other'
 'yahoo.co.uk_Other' 'yahoo.de_missing' 'cox.net_Android'
 'windstream.net_Windows' 'outlook.com_macOS' 'optonline.net_Other'
 'embarqmail.com_iOS' 'cox.net_Other' 'bellsouth.net_macOS'
 'embarqmail.com_Windows' 'suddenlink.net_Other' 'ymail.com_macOS'
 'hotmail.fr_Other' 'optonline.net_iOS' 'frontiernet.net_Other'
 'q.com_macOS' 'hotmail.de_Other' 'roadrunner.com_macOS'
 'cfl.rr.com_Other' 'rocketmail.com_Other' 'live.com_macOS'
 'att.net_Other' 'roadrunner.com_Windows' 'earthlink.net_Windows'
 'outlook.es_missing' 'juno.com_Other' 'hotmail.co.uk_missing'
 'att.net_Linux' 'netzero.net_Android' 'twc.com_Windows'
 'cableone.net_macOS' 'verizon.net_Other' 'aim.com_iOS' 'yahoo.es_missing'
 'ptd.net_Other' 'rocketmail.com_Windows' 'protonmail.com_missing'
 'centurylink.net_Windows' 'hotmail.co.uk_Other' 'netzero.com_Windows'
 'sbcglobal.net_Other' 'comcast.net_Linux' 'sc.rr.com_Android'
 'cfl.rr.com_iOS' 'cfl.rr.com_Windows' 'centurylink.net_Android'
 'rocketmail.com_macOS' 'embarqmail.com_macOS' 'ptd.net_iOS'
 'windstream.net_iOS' 'charter.net_Other' 'sc.rr.com_Windows'
 'yahoo.co.uk_iOS' 'mail.com_macOS' 'netzero.com_iOS'
 'outlook.com_Android' 'yahoo.co.uk_missing' 'q.com_Android'
 'netzero.net_macOS' 'msn.com_Linux' 'rocketmail.com_Android'
 'frontiernet.net_macOS' 'frontier.com_macOS' 'sbcglobal.net_Linux'
 'windstream.net_Other' 'att.net_Android' 'netzero.net_Windows'
 'yahoo.co.jp_Other' 'suddenlink.net_iOS' 'frontier.com_Android'
 'q.com_iOS' 'ptd.net_Windows' 'centurylink.net_iOS' 'twc.com_Android'
 'mail.com_iOS' 'aim.com_Android' 'centurylink.net_macOS' 'gmx.de_Windows'
 'frontiernet.net_Android' 'protonmail.com_Other' 'juno.com_iOS'
 'q.com_Other' 'mac.com_Other' 'gmail_Android' 'charter.net_Android'

In [149]:
# Define the combinations (feature1, feature2) and a short name prefix
combinations = [
    ('card_network', 'user_os', 'card_net_user_os'),
    ('card_network', 'is_identity_seen_before', 'card_net_id_seen'),
    ('card_type', 'user_os', 'card_type_user_os'),
    ('card_type', 'is_identity_seen_before', 'card_type_id_seen'),
    ('purchaser_email_domain', 'device_type', 'pemail_dev_type'),
    ('purchaser_email_domain', 'is_identity_seen_before', 'pemail_id_seen'),
    ('purchaser_email_domain', 'environment_risk', 'pemail_env_risk'),
    ('purchaser_email_domain', 'user_os', 'pemail_user_os'),
    ('is_identity_seen_before', 'user_browser', 'id_seen_user_browser'),
    ('user_os', 'user_browser', 'user_os_browser'),
    ('user_browser', 'environment_risk', 'browser_env_risk'),
    ('user_browser', 'card_type', 'browser_card_type'),
    ('time_diff_bins', 'time_hour', 'time_diff_bins_hour'),
    ('is_identity_seen_before', 'amt_bins', 'id_seen_amt_bin'),
]

# Convert numeric-like columns to string to avoid errors during concatenation
# (time_diff_bins and amt_bins may be numeric; time_hour is numeric but we treat as category)
for col1, col2, _ in combinations:
    if col1 in df.columns and df[col1].dtype in ['int64', 'float64']:
        df[col1] = df[col1].astype(str)
    if col2 in df.columns and df[col2].dtype in ['int64', 'float64']:
        df[col2] = df[col2].astype(str)

# Create the combined features
for col1, col2, new_name in combinations:
    df[new_name] = df[col1].astype(str) + '_' + df[col2].astype(str)

# The new features are categorical. You can later apply label encoding or target encoding.

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Data columns (total 41 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           590540 non-null  float64
 1   is_fraud                 590540 non-null  object
 2   transaction_time         590540 non-null  float64
 3   transaction_amount       590540 non-null  float64
 4   card_network             590540 non-null  object
 5   card_type                590540 non-null  object
 6   purchaser_email_domain   590540 non-null  object
 7   device_type              590540 non-null  object
 8   is_identity_seen_before  590540 non-null  object
 9   user_os                  590540 non-null  object
 10  user_browser             590540 non-null  object
 11  environment              590540 non-null  object
 12  environment_freq         590540 non-null  float64
 13  environment_risk         590540 non-null  object
 14  time_hour                590540 non-null  object
 15  time_day                 590540 non-null  float64
 16  time_diff                590540 non-null  float64
 17  time_diff_min            590540 non-null  float64
 18  amt_log                  590540 non-null  float64
 19  amt_bins                 590540 non-null  object
 20  new_day                  590540 non-null  bool
 21  day_id                   590540 non-null  float64
 22  day_of_week              590540 non-null  float64
 23  time_diff_log            590540 non-null  float64
 24  device_typ_os            590540 non-null  object
 25  known_env_risk           590540 non-null  object
 26  time_diff_bins           590540 non-null  object
 27  card_net_user_os         590540 non-null  object
 28  card_net_id_seen         590540 non-null  object
 29  card_type_user_os        590540 non-null  object
 30  card_type_id_seen        590540 non-null  object
 31  pemail_dev_type          590540 non-null  object
 32  pemail_id_seen           590540 non-null  object
 33  pemail_env_risk          590540 non-null  object
 34  pemail_user_os           590540 non-null  object
 35  id_seen_user_browser     590540 non-null  object
 36  user_os_browser          590540 non-null  object
 37  browser_env_risk         590540 non-null  object
 38  browser_card_type        590540 non-null  object
 39  time_diff_bins_hour      590540 non-null  object
 40  id_seen_amt_bin          590540 non-null  object
dtypes: bool(1), float64(11), object(29)
memory usage: 180.8+ MB

In [153]:
for i in df2.columns:
    '___________*************************_________'
    print(i)
    print(len(df[i].unique()))

    '___________***************_________'

card_network
5
card_type
5
purchaser_email_domain
60
device_type
3
is_identity_seen_before
3
user_os
7
user_browser
10
environment_risk
4
time_hour
24
amt_bins
10
device_typ_os
14
known_env_risk
10
time_diff_bins
10
card_net_user_os
34
card_net_id_seen
15
card_type_user_os
24
card_type_id_seen
13
pemail_dev_type
177
pemail_id_seen
178
pemail_env_risk
213
pemail_user_os
315
id_seen_user_browser
28
user_os_browser
37
browser_env_risk
19
browser_card_type
34
time_diff_bins_hour
240
id_seen_amt_bin
30